name: PIC CI

on:
    workflow_dispatch:

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositoryg
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      working-directory: ./challenge
      run: npm install

   

    - name: Run tests
      working-directory: ./challenge
      run: npm test
  securite-check:
    runs-on: ubuntu-latest
      
  