name: PIC CI

on:
    workflow_dispatch:

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositoryg
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      working-directory: ./challenge
      run: npm install

   

    - name: Run tests
      working-directory: ./challenge
      run: npm test

  security:
    needs: run_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master  
    - name: Run Snyk to check for vulnerabilities
      id: snyk
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  
      with:
        args: --all-projects
    
    - name: Upload Snyk results as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: snyk-results
        path: ${{ github.workspace }}/snyk-report.json   

  sonarcloud:
    needs: run_test
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  send_notification:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - name: Download Snyk results artifact
        uses: actions/download-artifact@v2
        with:
          name: snyk-results
          path: ${{ github.workspace }}
      
      - name: Read Snyk results
        id: read-snyk-results
        run: echo "::set-output name=snyk-results::$(cat ${{ github.workspace }}/snyk-report.json)"
      
      - name: Send notification
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>. Snyk Results: ${{ steps.read-snyk-results.outputs.snyk-results }}"
          footer: "Linked Repo <{repo_url}|{repo}>"
          notify_when: "failure"
          mention_users: "U0160UUNH8S,U0080UUAA9N"
          mention_users_when: "failure,warnings"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}      

   

  