name: PIC CI

on:
    workflow_dispatch:

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositoryg
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      working-directory: ./challenge
      run: npm install

   

    - name: Run tests
      working-directory: ./challenge
      run: npm test

  security:
    needs: run_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master  
    - name: Run Snyk to check for vulnerabilities
      id: snyk
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  
      with:
        args: --all-projects
    - name: Save Snyk output to file
      run: |
        echo "${{ steps.snyk.outputs.snyk-output }}" > snyk_output.txt    
   

  